### ISSUE TITLE
Support OpenXml files

### ISSUE THREAD

**Issue by sergey-tihon** [stef-levesque/vscode-zipexplorer#16]
Register `Explore Zip File` action for [OpenXML packages](https://en.wikipedia.org/wiki/Office_Open_XML_file_formats).
-  Word `.docx`, `.docm`
-  PowerPoint `.pptx`, `.pptm`
-  Excel `. xlsx`, `. xlsm`

**Comment by stef-levesque** [comment]
You can set your own file associations in your user settings.

I prefer not to do association to files that might be better served by other extensions.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/7251102/108291312-151db680-7160-11eb-843d-4a5bc6922081.png">

**Comment by sergey-tihon** [comment]
>  prefer not to do association to files that might be better served by other extensions.

Inspired by this `vscode-zipexplorer`, I decided to create new extension  specifically for OpenXml packages.

https://github.com/sergey-tihon/vscode-openxml-explorer
