### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by maria-matos** [stef-levesque/vscode-zipexplorer#17]
- Issue Type: `Bug`
- Extension Name: `vscode-zipexplorer`
- Extension Version: `0.3.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by stef-levesque** [comment]
Unfortunately, I can't do much without the data copied in the clipboard.
Please create another issue if this happen again.
